### ISSUE TITLE
Chat functionality 

### ISSUE THREAD

**Issue by Bearsaerker** [katanaml/llm-ollama-llamaindex-invoice-cpu#1]
I'm pretty new to LLMs and programming and teaching myself on the go what I need. I love the repository so far and it works like a charm. The past few days I *tried* to implement a chat functionality by myself but my coding knowledge is way too bad for doing so. How hard would it be to incorporate that functionality?

**Comment by abaranovskis-redsamurai** [comment]
hey. you can implement chat with memory using LlamaIndex and Ollama. Here is simple example (check conversational RAG point): https://medium.com/poatek/building-open-source-llm-based-chatbots-using-llama-index-e6de9999ee76
