### ISSUE TITLE
incompatible version of langchain

### ISSUE THREAD

**Issue by robinmordasiewicz** [katanaml/llm-ollama-llamaindex-invoice-cpu#2]
The following error us produced when trying to run the example.
ImportError: cannot import name '_is_openai_v1' from 'langchain_community.embeddings.openai'

The version of langchain in the requirements.txt should be version 0.1.0

**Comment by abaranovskis-redsamurai** [comment]
Issue not reproduced. On my environment combination:

llama-index==0.9.15
langchain==0.0.350

works Ok.
