### ISSUE TITLE
Fix README.md for docker compose up -d command for weaviate installation

### ISSUE THREAD

**Issue by sage-khan** [katanaml/llm-ollama-llamaindex-invoice-cpu#4]
I think the docker compose up -d  for weaviate needs to be docker-compose up -d

Regards
![image](https://github.com/katanaml/llm-ollama-llamaindex-invoice-cpu/assets/82077318/9eee8a1c-b6fa-4da5-8a6d-e367278996d4)

**Comment by abaranovskis-redsamurai** [comment]
It works for me with: docker compose up -d
