### ISSUE TITLE
Running on windows machine giving error

### ISSUE THREAD

**Issue by ritesh7911** [katanaml/llm-ollama-llamaindex-invoice-cpu#5]
As per readme file. I ran the command but it is giving below error 
"requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='192.168.68.110', port=11434): Max retries exceeded with url: /api/generate/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001D9C5576530>, 'Connection to 192.168.68.110 timed out. (connect timeout=None)'))"

**Comment by abaranovskis-redsamurai** [comment]
Replace Ollama host as per your system, probably 127.0.0.1 in config file: https://github.com/katanaml/llm-ollama-llamaindex-invoice-cpu/blob/main/config.yml

this is sample app, main repo is here: https://github.com/katanaml/sparrow
